// Shop-Items (offizieller Shop /shop) — Account-Features mit Vibes ✨ freikaufen.
// Manche permanent, manche pro Aktion.

export const PREMIUM_ITEMS = [
  // ---- Profilbild-Slots (3 Stufen) ----
  {
    kind: "extra_pic_slots",
    name: "+5 Profilbild-Slots",
    emoji: "📸",
    price: 150,
    description: "Lade bis zu 14 statt 9 Profilbilder hoch. Permanent.",
    permanent: true,
    bonus: 5,
    group: "slots",
  },
  {
    kind: "extra_pic_slots_xl",
    name: "+10 Profilbild-Slots",
    emoji: "📷",
    price: 280,
    description: "Lade insgesamt 24 statt 9 Profilbilder hoch. Permanent (zusätzlich).",
    permanent: true,
    bonus: 10,
    group: "slots",
  },
  {
    kind: "extra_pic_slots_mega",
    name: "+25 Profilbild-Slots (Mega)",
    emoji: "🖼️",
    price: 600,
    description: "Bis zu 49 Profilbilder. Für ausführliche Galerie-Sammler. Permanent (zusätzlich).",
    permanent: true,
    bonus: 25,
    group: "slots",
  },

  // ---- Name & Identität ----
  {
    kind: "displayname_change",
    name: "Anzeigename ändern",
    emoji: "🏷️",
    price: 100,
    description: "Neuer Anzeigename — muss einzigartig sein. Pro Änderung.",
    permanent: false,
    group: "name",
  },
  {
    kind: "displayname_3pack",
    name: "Anzeigename-3er-Pack",
    emoji: "🎫",
    price: 220,
    description: "3 Namens-Wechsel auf Vorrat (sonst 3×100=300 ✨). Speichert 3 Guthaben.",
    permanent: false,
    pack: 3,
    group: "name",
  },
  {
    kind: "username_change",
    name: "@username ändern (1×/Jahr)",
    emoji: "📛",
    price: 500,
    description: "Komplett neuer Handle. ACHTUNG: alte Links zeigen ins Leere! Max 1×/Jahr.",
    permanent: false,
    cooldownDays: 365,
    group: "name",
  },
  {
    kind: "username_change_fast",
    name: "@username sofort ändern",
    emoji: "⚡",
    price: 1500,
    description: "Username-Wechsel ohne 1-Jahr-Sperre. Für Wechsler die's eilig haben.",
    permanent: false,
    group: "name",
  },
  {
    kind: "vanity_url",
    name: "Vanity-URL freischalten",
    emoji: "🔗",
    price: 300,
    description: "Eigener kurzer Profil-Link statt /u/dein_name (kommt in Kürze).",
    permanent: true,
    group: "name",
  },

  // ---- Status & Texte ----
  {
    kind: "custom_status",
    name: "Eigener Status-Text",
    emoji: "💬",
    price: 50,
    description: "Schreib deinen eigenen Status (statt nur vorgegebenen). Kostet pro Setzen.",
    permanent: false,
    group: "status",
  },
  {
    kind: "status_slot",
    name: "Status-Lieblings-Slots",
    emoji: "⭐",
    price: 100,
    description: "Speichere bis zu 3 Lieblings-Status für Schnellzugriff. Permanent.",
    permanent: true,
    group: "status",
  },
  {
    kind: "bio_xl",
    name: "Lange Bio (1000 Zeichen)",
    emoji: "📝",
    price: 120,
    description: "Bio bis 1000 statt 200 Zeichen. Erzähl deine Story. Permanent.",
    permanent: true,
    group: "status",
  },
  {
    kind: "presence_invisible",
    name: "Dauer-Unsichtbar",
    emoji: "👻",
    price: 250,
    description: "Niemand sieht wann du online bist. Du siehst andere weiterhin. Permanent.",
    permanent: true,
    group: "status",
  },

  // ---- Badges & Rahmen ----
  {
    kind: "badge_gold",
    name: "Gold-Badge",
    emoji: "🥇",
    price: 800,
    description: "Goldener Stern neben deinem Namen — sichtbar überall. Permanent.",
    permanent: true,
    group: "badges",
  },
  {
    kind: "badge_diamond",
    name: "Diamant-Badge",
    emoji: "💎",
    price: 2500,
    description: "Diamant neben deinem Namen — premium status. Permanent.",
    permanent: true,
    group: "badges",
  },
  {
    kind: "frame_rainbow",
    name: "Regenbogen-Rahmen",
    emoji: "🌈",
    price: 350,
    description: "Animierter Regenbogen-Rahmen um dein Profilbild. Permanent.",
    permanent: true,
    group: "badges",
  },
  {
    kind: "frame_neon",
    name: "Neon-Glow-Rahmen",
    emoji: "🟪",
    price: 250,
    description: "Pulsierender Neon-Glow um dein Profilbild. Permanent.",
    permanent: true,
    group: "badges",
  },
  {
    kind: "frame_gold",
    name: "Gold-Rahmen",
    emoji: "🟨",
    price: 220,
    description: "Eleganter Gold-Rahmen um dein Profilbild. Permanent.",
    permanent: true,
    group: "badges",
  },
];

export const PREMIUM_MAP = Object.fromEntries(PREMIUM_ITEMS.map((p) => [p.kind, p]));

// Gruppen-Labels für die UI
export const PREMIUM_GROUPS = [
  { id: "slots",  label: "📷 Profilbild-Slots" },
  { id: "name",   label: "🏷️ Name & Identität" },
  { id: "status", label: "💬 Status & Bio" },
  { id: "badges", label: "🥇 Badges & Rahmen" },
];
